# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - junction-2021(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - azure-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: npm install
        run: |
          npm install

      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: junction-2021
          slot-name: Production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e441cfd75db64c62b09bcca1ea17f473 }}
          package: .
